// Package v0 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v0

// APIError defines model for APIError.
type APIError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GenerateURLRequest defines model for GenerateURLRequest.
type GenerateURLRequest struct {
	Url string `json:"url"`
}

// GenerateURLResponse defines model for GenerateURLResponse.
type GenerateURLResponse struct {
	ExpireTime       string `json:"expireTime"`
	GeneratedTinyURL string `json:"generatedTinyURL"`
}

// GenerateURLJSONRequestBody defines body for GenerateURL for application/json ContentType.
type GenerateURLJSONRequestBody = GenerateURLRequest
