// Package v0 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v0

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate a tiny url
	// (POST /generate)
	GenerateURL(ctx echo.Context) error
	// Deletes a tiny url
	// (DELETE /{urlKey})
	DeleteURL(ctx echo.Context, urlKey string) error
	// redirects to long url.
	// (GET /{urlKey})
	GetURL(ctx echo.Context, urlKey string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GenerateURL converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateURL(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GenerateURL(ctx)
	return err
}

// DeleteURL converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteURL(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "urlKey" -------------
	var urlKey string

	err = runtime.BindStyledParameterWithLocation("simple", false, "urlKey", runtime.ParamLocationPath, ctx.Param("urlKey"), &urlKey)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter urlKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteURL(ctx, urlKey)
	return err
}

// GetURL converts echo context to params.
func (w *ServerInterfaceWrapper) GetURL(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "urlKey" -------------
	var urlKey string

	err = runtime.BindStyledParameterWithLocation("simple", false, "urlKey", runtime.ParamLocationPath, ctx.Param("urlKey"), &urlKey)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter urlKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetURL(ctx, urlKey)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/generate", wrapper.GenerateURL)
	router.DELETE(baseURL+"/:urlKey", wrapper.DeleteURL)
	router.GET(baseURL+"/:urlKey", wrapper.GetURL)

}
