openapi: 3.0.3
info:
  title: Tiny URL Service
  description: |-
    API for shortening a URL
  contact:
    email: vaishakpdinesh@gmail.com
  version: v0.0
servers:
  - url: /tinyurlsvc
paths:
  /generate:
    post:
      summary: Generate a tiny url
      description: Generates a tiny url from the input
      operationId: GenerateURL
      requestBody:
        description: schema for a generate request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateURLRequest'
      responses:
        '201':
          description: successfully generated a url.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateURLResponse'
  /{urlKey}:
    parameters:
      - name: urlKey
        in: path
        description: key generated for the long url
        required: true
        schema:
          type: string
          example: 2AYAhB
    get:
      summary: redirects to long url.
      description: redirects the client to the long url.
      operationId: GetURL
      responses:
        '302':
          description: successfully redirects to the long url.
        '404':
          description: url not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    delete:
      summary: Deletes a tiny url
      description: Deletes a tiny url generated for a long url
      operationId: DeleteURL
      responses:
        '204':
          description: successfully deletes a tiny url
        '404':
          description: url not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

components:
  schemas:
    GenerateURLRequest:
      type: object
      required:
        - url
        - liveForever
      properties:
        url:
          type: string
          example: https://google.com
          minLength: 3
        liveForever:
          type: boolean
          description: boolean indicating whether the generated url will not expire. Not required as the API will default to false.
          default: false
          example: false
    GenerateURLResponse:
      type: object
      required:
        - generatedTinyURL
      properties:
        generatedTinyURL:
          type: string
        expireTime:
          type: string
    APIError:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
        message:
          type: string