openapi: 3.0.3
info:
  title: Tiny URL Service
  description: |-
    API for shortening a URL
  contact:
    email: vaishakpdinesh@gmail.com
  version: v0.0
servers:
  - url: /api/v0
paths:
  /generate:
    post:
      summary: Generate a tiny url
      description: Generates a tiny url from the input
      operationId: GenerateURL
      requestBody:
        description: schema for a generate request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateURLRequest'
      responses:
        '201':
          description: successfully generated a url.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateURLResponse'

components:
  schemas:
    GenerateURLRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          example: https://google.com
          minLength: 3
    GenerateURLResponse:
      type: object
      required:
        - generatedTinyURL
        - expireTime
      properties:
        generatedTinyURL:
          type: string
        expireTime:
          type: string
    APIError:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
        message:
          type: string